# Generated by Django 3.1.2 on 2020-10-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jwt',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
