# Generated by Django 3.1.2 on 2020-10-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='code',
            new_name='room_code',
        ),
    ]
